import { Poppins } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: [ "300", "400", "500", "600", "700" , "900"],
});

export const metadata = {
  title: "Food Cheetah - Food Ordering App",
  description: "Generated by create next app",
  icons: {
    icon: "/Chester-Cheetah-LOGO.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
