import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { Toaster } from "../components/ui/sonner";
import SessionWrapper from "@/components/authComponents/SessionWrapper";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "900"],
});

export const metadata = {
  title: "Food Cheetah - Food Ordering App",
  description: "Generated by create next app",
  icons: {
    icon: "/Chester-Cheetah-LOGO.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <SessionWrapper>
          <Navbar />
          <div>{children}</div>
          <Toaster richColors />
          <Footer />
        </SessionWrapper>
      </body>
    </html>
  );
}
